// <auto-generated />
using System;
using BeginningCSharpAndDotNET_17_1_CodeFirstDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeginningCSharpAndDotNET_17_1_CodeFirstDatabase.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeginningCSharpAndDotNET_17_1_CodeFirstDatabase.Book", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BeginningCSharpAndDotNET_17_1_CodeFirstDatabase.Stock", b =>
                {
                    b.Property<int>("StockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemCode")
                        .HasColumnType("int");

                    b.Property<int>("OnHand")
                        .HasColumnType("int");

                    b.Property<int>("OnOrder")
                        .HasColumnType("int");

                    b.Property<int?>("StoreID")
                        .HasColumnType("int");

                    b.HasKey("StockID");

                    b.HasIndex("ItemCode");

                    b.HasIndex("StoreID");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("BeginningCSharpAndDotNET_17_1_CodeFirstDatabase.Store", b =>
                {
                    b.Property<int>("StoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StoreID");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("BeginningCSharpAndDotNET_17_1_CodeFirstDatabase.Stock", b =>
                {
                    b.HasOne("BeginningCSharpAndDotNET_17_1_CodeFirstDatabase.Book", "Item")
                        .WithMany()
                        .HasForeignKey("ItemCode");

                    b.HasOne("BeginningCSharpAndDotNET_17_1_CodeFirstDatabase.Store", null)
                        .WithMany("Inventory")
                        .HasForeignKey("StoreID");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("BeginningCSharpAndDotNET_17_1_CodeFirstDatabase.Store", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
